ETICARET.WebUI/Controllers/CartController.cs
using ETICARET.Business.Abstract;
using ETICARET.Entities;
using ETICARET.WebUI.Extensions;
using ETICARET.WebUI.Identity;
using ETICARET.WebUI.Models;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace ETICARET.WebUI.Controllers
{
    public class CartController : Controller
    {
        private ICartService _cartService;
        private IProductService _productService;
        private IOrderService _orderService;
        private UserManager<ApplicationUser> _userManager;

        public CartController(ICartService cartService,IProductService productService,IOrderService orderService,UserManager<ApplicationUser> userManager)
        {
            _cartService = cartService;
            _productService = productService;
            _orderService = orderService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            return View(
                new CartModel()
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(x => new CartItemModel()
                    {
                        CartItemId = x.Id,
                        ProductId = x.Product.Id,
                        Name = x.Product.Name,
                        Price = x.Product.Price,
                        ImageUrl = x.Product.Images[0].ImageUrl,
                        Quantity = x.Quantity
                    }).ToList()
                }
                );
        }

        public IActionResult AddToCart(int productId,int quantity)
        {
            _cartService.AddToCart(_userManager.GetUserId(User), productId, quantity); 
            return RedirectToAction("Index");
        }

        public IActionResult DeleteFromCart(int productId)
        {
            _cartService.DeleteFromCart(_userManager.GetUserId(User), productId);
            return RedirectToAction("Index");
        }

        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            OrderModel orderModel = new OrderModel();

            orderModel.CartModel = new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(x => new CartItemModel()
                {
                    CartItemId = x.Id,
                    ProductId = x.Product.Id,
                    Name = x.Product.Name,
                    Price = x.Product.Price,
                    ImageUrl = x.Product.Images[0].ImageUrl,
                    Quantity = x.Quantity
                }).ToList()
            };

            return View(orderModel);
        }

        [HttpPost]
        public IActionResult Checkout(OrderModel model, string paymentMethod)
        {
            ModelState.Remove("CartModel");

            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var cart = _cartService.GetCartByUserId(userId);

                model.CartModel = new CartModel()
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(x => new CartItemModel()
                    {
                        CartItemId = x.Id,
                        ProductId = x.Product.Id,
                        Name = x.Product.Name,
                        Price = x.Product.Price,
                        ImageUrl = x.Product.Images[0].ImageUrl,
                        Quantity = x.Quantity
                    }).ToList()
                };

                if (paymentMethod == "credit")
                {
                    var payment = PaymentProccess(model);

                    if (payment.Result.Status == "success")
                    {
                        SaveOrder(model,payment,userId);
                        ClearCart(cart.Id.ToString());
                        TempData.Put("message", new ResultModel()
                        {
                            Title = "Order Completed",
                            Message = "Your order has been completed successfully",
                            Css = "success"
                        });
                    }
                    else
                    {
                        TempData.Put("message", new ResultModel()
                        {
                            Title = "Order Uncompleted",
                            Message = "Your order could not be completed",
                            Css = "danger"
                        });
                    }
                }
                else
                {

                    SaveOrder(model,userId);
                    ClearCart(cart.Id.ToString());

                    TempData.Put("message", new ResultModel()
                    {
                        Title = "Order Completed",
                        Message = "Your order has been completed successfully",
                        Css = "success"
                    });
                   
                }

            }

            return View(model);
        }

        private void ClearCart(string id)
        {
            _cartService.ClearCart(id);
        }

        // EFT
        private void SaveOrder(OrderModel model, string userId)
        {
            Order order = new Order()
            {
                OrderNumber = Guid.NewGuid().ToString(),
                OrderState = EnumOrderState.completed,
                PaymentTypes = EnumPaymentTypes.Eft,
                PaymentToken = Guid.NewGuid().ToString(),
                ConversionId = Guid.NewGuid().ToString(),
                PaymentId = Guid.NewGuid().ToString(),
                OrderNote = model.OrderNote,
                OrderDate = DateTime.Now,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Address = model.Address,
                City = model.City,
                Email = model.Email,
                Phone = model.Phone,
                UserId = userId
            };

            foreach (var cartItem in model.CartModel.CartItems)
            {
                var orderItem = new Entities.OrderItem()
                {
                    Price = cartItem.Price,
                    Quantity = cartItem.Quantity,
                    ProductId = cartItem.ProductId,
                };

                order.OrderItems.Add(orderItem);
            }

            _orderService.Create(order);

        }

        // Credit Card
        private void SaveOrder(OrderModel model, Task<Payment> payment, string userId)
        {
            Order order = new Order()
            {
                OrderNumber = Guid.NewGuid().ToString(),
                OrderState = EnumOrderState.completed,
                PaymentTypes = EnumPaymentTypes.CreditCard,
                PaymentToken = Guid.NewGuid().ToString(),
                ConversionId = payment.Result.ConversationId,
                PaymentId = payment.Result.PaymentId,
                OrderNote = model.OrderNote,
                OrderDate = DateTime.Now,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Address = model.Address,
                City = model.City,
                Email = model.Email,
                Phone = model.Phone,
                UserId = userId
            };

            foreach (var cartItem in model.CartModel.CartItems)
            {
                var orderItem = new Entities.OrderItem()
                {
                    Price = cartItem.Price,
                    Quantity = cartItem.Quantity,
                    ProductId = cartItem.ProductId,
                };

                order.OrderItems.Add(orderItem);
            }

            _orderService.Create(order);
        }

        private async Task<Payment> PaymentProccess(OrderModel model)
        {
            Options options = new Options()
            {
                BaseUrl = "https://sandbox-api.iyzipay.com",
                ApiKey = "sandbox-cNnJEaoyNt0sCREL4nOq8PajTLQwWeXz",
                SecretKey = "sandbox-cmJxJfaGlVarqNV3c5ZQcMTwVNh8qswx"
            };

            string externalIpString = new WebClient().DownloadString("http://icanhazip.com").Replace("\\r\\n", "").Replace("\\n", "").Trim();
            var externalIp = IPAddress.Parse(externalIpString);

            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = Guid.NewGuid().ToString();
            request.Price = model.CartModel.TotalPrice().ToString().Split(',')[0];
            request.PaidPrice = model.CartModel.TotalPrice().ToString().Split(',')[0];
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = model.CartModel.CartId.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();
            request.PaymentChannel = PaymentChannel.WEB.ToString();

            PaymentCard paymentCard = new PaymentCard()
            {
                CardHolderName = model.CardName,
                CardNumber = model.CardNumber,
                ExpireYear = model.ExprationYear,
                ExpireMonth = model.ExprationMonth,
                Cvc = model.CVV,
                RegisterCard = 0
            };

            

            request.PaymentCard = paymentCard;

            Buyer buyer = new Buyer()
            {
                Id = _userManager.GetUserId(User),
                Name = model.FirstName,
                Surname = model.LastName,
                GsmNumber = model.Phone,
                Email = model.Email,
                IdentityNumber = "11111111111",
                RegistrationAddress = model.Address,

ETICARET.WebUI/Controllers/ShopController.cs
using ETICARET.Business.Abstract;
using ETICARET.Entities;
using ETICARET.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace ETICARET.WebUI.Controllers
{
    public class ShopController : Controller
    {
        private IProductService _productService;

        public ShopController(IProductService productService)
        {
            _productService = productService;
        }

        [Route("products/{category?}")]
        public IActionResult List(string category, int page = 1)
        {
            const int pageSize = 5;

            var products = new ProductListModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems = _productService.GetCountByCategory(category),
                    ItemsPerPage = pageSize,
                    CurrentCategory = category,
                    CurrentPage = page
                },
                Products = _productService.GetProductByCategory(category, page, pageSize)
            };

            return View(products);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            Product product = _productService.GetProductDetail(id.Value);
            if (product == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            return View(new ProductDetailsModel()
            {
                Product = product,
                Categories = product.ProductCategories.Select(i => i.Category).ToList(),
                Comments = product.Comments
            });
        }
    }
}

ETICARET.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width-device-width,initial-scale=1.0" />
        <title>@ViewData["Title"] - Üçüncübinyıl ETİCARET</title>
        <link rel="stylesheet" href="/modules/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="/modules/jquery/dist/jquery.min.js" ></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <!-- font awesome --> 
    </head>
    <body>
        <partial name="_navbar" />
        <div class="container pageContainer">
            @if(TempData["message"] != null)
            {
                /* error ve success mesajları */
                <partial name="_resultMessage" model="@(TempData.Get<ResultModel>("message"))" />
            }
            @RenderBody()
        </div>


    <script src="/modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts",required:false)
    </body>
</html>

ETICARET.WebUI/Views/Shared/_PartialComments.cshtml
@using System.Security.Claims

@model List<Comment>

@{
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var usernames = ViewBag.Usernames as Dictionary<string, string> ?? new Dictionary<string, string>();
}

@if (User.Identity.IsAuthenticated)
{
    <div class="row">
        <div class="col-md-12">
            <hr />
        </div>
        <div class="row">
            <div class="col-md-12">
                <input type="text" id="new_comment_text" class="form-control mb-2" placeholder="Your Comments..." />
                <span class="input-group-btn mt-2">
                    <button type="button" class="btn btn-success" onclick="doComment(this,'new_clicked',-1)">
                        <span class="fas fas-share"></span> Submit
                    </button>
                </span>
            </div>
        </div>
    </div>
}
@if (Model.Count > 0)
{
    @foreach (var comment in Model)
    {
        <div class="d-flex">
            <div class="flex-grow-1 ms-1 mt-3">
                <h6 class="col-md-12">
                    <span>@(usernames.ContainsKey(comment.UserId) ? usernames[comment.UserId] : "Anonim")</span>
                    <small class="text-muted">
                        <i>@comment.CreateOn.ToString("ddd, dd MMMM yyyy")</i>
                    </small>
                </h6>
                <span class="col-md-10" id="comment_text_@comment.Id" contenteditable="false">
                    @comment.Text
                </span>
                @if (User.Identity.IsAuthenticated && userId == comment.UserId)
                {
                    <span class="col-md-2 float-end">
                        <button type="button" class="btn btn-warning btn-xs" data-edit-mode="false" onclick="doComment(this,'edit_clicked',@comment.Id,'#comment_text_@comment.Id')">
                            <span class="fas fa-edit fa-xs"></span>
                        </button>
                        <button type="button" class="btn btn-warning btn-xs" data-edit-mode="false" onclick="doComment(this,'delete_clicked',@comment.Id,'#comment_text_@comment.Id')">
                            <span class="fas fa-trash fa-xs"></span>
                        </button>
                    </span>
                }
            </div>
        </div>
    }
}
else
{
    <div class="alert alert-info mt-2">
        Düşüncelerini Yaz
    </div>
}

ETICARET.WebUI/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ETİCARET</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
            <div class="col-md-9">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/products/all">Products</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" asp-controller="Admin" asp-action="CreateProduct">Add Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="/admin/products">Admin Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" asp-controller="Admin" asp-action="CreateCategory">Create Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" asp-controller="Admin" asp-action="CategoryList">Category List</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" asp-controller="Cart" asp-action="Index">Cart</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" asp-controller="Cart" asp-action="GetOrders">Orders</a>
                            </li>
                        }
                    }
                    <li class="nav-item dropdown">
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                            <a class="nav-link" asp-controller="Shop" asp-action="List">Products</a>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 d-flex login-register">
                <ul class="navbar-nav mr-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-controller="Account" asp-action="Manage">@User.Identity.Name</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    }
                </ul>
            </div>
           
        </div>
    </div>
</nav>

ETICARET.WebUI/Views/Shared/_products.cshtml
@model Product

<div class="col-md-3 mt-3">
    <div class="card">
        @{
            var image = Model.Images.Find(img => img.ProductId == Model.Id);
        }
        @if(image != null)
        {
            <img src="~/img/@image.ImageUrl" />
        }
        else
        {
            <img src="~/img/placeholder.jpg" />
        }
        <div class="card-body">
            <h4 class="card-title">
                <a asp-controller="Shop" asp-action="Details"  asp-route-id="@Model.Id">
                    @Model.Name
                </a>
            </h4>
            <div class="price-box d-flex justify-content-end">
                <small class="text-muted price">
                    @Model.Price
                </small>
            </div>
          
        </div>
        <div class="card-footer text-center">
            <a class="btn btn-outline-primary btn-sm" asp-controller="Shop" asp-action="Details" asp-route-id="@Model.Id">
                Details
            </a>
            @if (User.Identity.IsAuthenticated)
            {
                @if (!User.IsInRole("admin"))
                {
                    <form asp-controller="Cart" asp-action="AddToCart" method="POST" style="display:inline">
                        <input type="hidden" name="productId" value="@Model.Id" />
                        <input type="hidden" name="quantity" value="1" />
                        <button type="submit" class="btn btn-outline-primary btn-sm ms-3">Add To Cart</button>
                    </form>
                }
            }
        </div>
    </div>
</div>

ETICARET.WebUI/Views/Shared/_resultMessage.cshtml
@model ResultModel
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-@Model.Css">
            <h4 class="alert-title">@Model.Title</h4>
            <p>@Model.Message</p>
        </div>
    </div>
</div>

ETICARET.WebUI/Views/Shared/_slider.cshtml
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
            <img src="~/img/slider1.png" class="min-vw-100" alt="Slider 1">
    </div>
    <div class="carousel-item">
            <img src="~/img/slider2.png" class="min-vw-100" alt="Slider 2">
     </div>
    <div class="carousel-item">
            <img src="~/img/slider3.png" class="min-vw-100" alt="Slider 3">
    </div>
  </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleSlidesOnly" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleSlidesOnly" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>